name: CI/CD DND Character Manager

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run: 
    shell: bash

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: peclarke/dnd-character-manager

jobs:
  build:
    name: Build, Test, Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make sure the project is building
        run: npm run build

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.WORKING_DIRECTORY }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest